spring.application.name=restaurante

spring.datasource.url=jdbc:postgresql://localhost:5432/tech_challenge
spring.datasource.username=postgres
spring.datasource.password=johnnydepps2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

